version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs:latest .
      - docker tag 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs:latest 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs:latest
      
   post_build:
     commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs:latest
      - echo Writing image definitions file...
      - printf '[{"name":"demonodejs","imageUri":"%s"}]' 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs:latest > imagedefinitions.json
      - cat imagedefinitions.json 
 

      

      
