version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password | docker login --username AWS --password-stdin 762218330168.dkr.ecr.us-east-1.amazonaws.com
      - 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs:latest .
      - docker tag 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs:latest 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs:latest
      - docker push 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' 762218330168.dkr.ecr.us-east-1.amazonaws.com/richard_nodejs:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json